function outside = getOutside(text, btwnChars)
    outside = Str.eraseBtwn(text, ...
        [btwnChars(:,1); btwnChars(:,1)], ...
        [btwnChars(:,2); btwnChars(:,2)], 'inclusive');
    outside = outside';
end