function key = loadKey
    raw = [{{'q'}, @Frmt.str}; ...
        {{'C'}, @Frmt.cat}; ...
        {{'L'}, @Frmt.log}; ...
        {{'t'}, @Frmt.table}; ...
        {{'r'}, @Frmt.cell}; ...
        {{'D', 'T'}, @Frmt.clock}; ...
        {{'d', 'I', 'u', 'n', 'o', 'x', 'f', 'e', 'E', 'g', 'G'}, @Frmt.num}];
    key = cell2table(raw, 'VariableNames', {'typeID', 'fcnHndl'});
    key.Properties.VariableDescriptions = {'type identifiers (primarily from textscan)', 'string to datatype conversion functions'};
end