function key = loadDurKey
    raw = [{{"seconds", "second", "secs", "sec", "s"}, @Time.secs, "Seconds"}; ...
           {{"minutes", "minute", "mins", "min", "m"}, @Time.mins, "Minutes"}; ...
           {{"hours", "hour", "hrs", "hr", "h"}, @Time.hrs, "Hours"}; ...
           {{"days", "day", "d"}, @Time.days, "Days"}; ...
           {{"weeks", "week", "wks", "wk", "w"}, @Time.wks, "Weeks"}; ...
           {{"months", "month", "mnths", "mnth", "mths", "mth"}, @Time.mths, "Months"}; ...
           {{"years", "year", "yrs", "yr", "y"}, @Time.yrs, "Years"}]; %#ok<CLARRSTR>
    
    key = cell2table(raw, 'VariableNames', {'txtID', 'convertHndl', 'durName'});
    key.Properties.VariableDescriptions = {'text indicating unit of duration', ...
        'string to duration conversion function', 'name of duration'};
    key.Properties.RowNames = string(key.durName)';
end